[[main]]
  identifier = "posts"
  name = "博客收纳盒"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "时光机"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "光影集"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "艺术"
  url = "gallery/art"

[[main]]
  parent = "gallery"
  name = "定格"
  url = "gallery/photo"

[[main]]
  identifier = "publication"
  name = "出版物"
  url = "publication"
  weight = 4

[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 5

